version: "3.8"

services:
  grocy:
    image: linuxserver/grocy:latest
    container_name: grocy-dev
    restart: unless-stopped
    ports:
      - "9192:80"
    environment:
      - TZ=UTC
      - PUID=1000
      - PGID=1000
    volumes:
      - ./.grocy-data:/config
    networks:
      - grocy-network

networks:
  grocy-network:
    name: grocy-dev-network
    driver: bridge
