default_config:

# Enable remote debugging
debugpy:
  host: 0.0.0.0
  port: 5678
  start: true
  wait: false

logger:
  default: info
  logs:
    custom_components.grocy: debug
    pygrocy.grocy_api_client: debug
